name: ci

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Run test with Maven
        run: mvn test
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ vars.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nkh1010/${{ vars.IMAGE_NAME }}:latest
          platforms: linux/x86_64
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ vars.IMAGE_NAME }}:master
          cache-to: type=inline

      - name: Inspect image
        run: |
          docker pull nkh1010/${{ vars.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          docker image inspect nkh1010/${{ vars.IMAGE_NAME}}:${{ steps.meta.outputs.version }}    

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          bash ./git_update.sh -v major

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker ${{vars.GAR_LOCATION}}-docker.pkg.dev --quiet

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag nkh1010/${{vars.IMAGE_NAME}}:${{ steps.meta.outputs.version }} ${{vars.GAR_LOCATION}}-docker.pkg.dev/${{ vars.PROJECT_ID }}/nkh-startsteps/ecommerce/${{vars.IMAGE_NAME}}:${{ steps.meta.outputs.version }}
          docker tag nkh1010/${{vars.IMAGE_NAME}}:${{ steps.meta.outputs.version }} ${{vars.GAR_LOCATION}}-docker.pkg.dev/${{ vars.PROJECT_ID }}/nkh-startsteps/ecommerce/${{vars.IMAGE_NAME}}:$GIT_TAG
          docker push ${{vars.GAR_LOCATION}}-docker.pkg.dev/${{ vars.PROJECT_ID }}/nkh-startsteps/ecommerce/${{vars.IMAGE_NAME}}:${{ steps.meta.outputs.version }}
          docker push ${{vars.GAR_LOCATION}}-docker.pkg.dev/${{ vars.PROJECT_ID }}/nkh-startsteps/ecommerce/${{vars.IMAGE_NAME}}:$GIT_TAG